services:
  go-bank-api:
    build:
      context: .
      dockerfile: local.Dockerfile
    pull_policy: always
    container_name: go-bank-api
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env
    